name: Get Data
on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * 7"
jobs:
  get-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        run: npm install
      - name: Get Data
        run: npm run scrape
      - name: Commit
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git pull
          git status
          git add .
          git commit -m "Get Data"
          git push